services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d/
    networks:
      - prod-promo-bot-network
  bot:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    command: npm run prod
    networks:
      - prod-promo-bot-network
networks:
  prod-promo-bot-network:
    driver: bridge
volumes:
  postgres_data:
