services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: attic_promo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-promo-bot-network
  bot:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ".:/usr/src"
    env_file:
      - .env.dev
    command: npm run dev
    networks:
      - dev-promo-bot-network
networks:
  dev-promo-bot-network:
    driver: bridge
volumes:
  postgres_data:
