

CREATE TABLE cases (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id BIGINT NOT NULL,
    caption TEXT,
    videonote TEXT,
    video TEXT,
    photo TEXT,
    audionote TEXT,
    audio TEXT
);

CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    bot_id BIGINT NOT NULL,
    first_name TEXT,
    last_name TEXT,
    username TEXT,
    added_at TIMESTAMPTZ DEFAULT NOW(),
    last_state TEXT,
    current_state TEXT
);

CREATE UNIQUE INDEX uniq_users_id_bot_id
ON users (id, bot_id);

CREATE OR REPLACE FUNCTION set_previous_state()
RETURNS trigger AS $$
BEGIN
    IF NEW.current_state IS DISTINCT FROM OLD.current_state THEN
        NEW.last_state := OLD.current_state;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_set_previous_state
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_previous_state();
