

CREATE TABLE cases (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id BIGINT NOT NULL,
    topic TEXT NOT NULL,
    creater_id BIGINT NOT NULL,
    caption TEXT,
    saved BOOLEAN DEFAULT FALSE
);

CREATE TABLE users (
    id BIGINT NOT NULL,
    bot_id BIGINT NOT NULL,
    first_name TEXT,
    last_name TEXT,
    username TEXT,
    added_at BIGINT,
    last_update BIGINT,
    previous_state TEXT,
    current_state TEXT
);

ALTER TABLE users
ADD CONSTRAINT user_bot_id_pk PRIMARY KEY (id, bot_id);

CREATE UNIQUE INDEX uniq_users_id_bot_id
ON users (id, bot_id);

CREATE OR REPLACE FUNCTION set_previous_state()
RETURNS trigger AS $$
BEGIN
    IF NEW.current_state IS DISTINCT FROM OLD.current_state THEN
        NEW.previous_state := OLD.current_state;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_set_previous_state
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_previous_state();

CREATE TABLE media (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id BIGINT NOT NULL,
    message_id TEXT NOT NULL,
    media_type TEXT NOT NULL,
    file_id TEXT NOT NULL
);

CREATE INDEX idx_media_message_id_bigint
ON media ((message_id::BIGINT));
