import type { Database } from '#root/database/index.js'
import type { User } from '@grammyjs/types'
import { getBotId } from '#root/bot/helpers/botId.js'

// CREATE TABLE cases (
//     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     bot_id BIGINT NOT NULL,
//     creater_id BIGINT NOT NULL,
//     topic TEXT,
//     caption TEXT,
//     videonote TEXT,
//     video TEXT,
//     photo TEXT,
//     audionote TEXT,
//     audio TEXT,
//     saved BOOLEAN DEFAULT FALSE,
// );

// CREATE TABLE users (
//     id BIGINT PRIMARY KEY,
//     bot_id BIGINT NOT NULL,
//     first_name TEXT,
//     last_name TEXT,
//     username TEXT,
//     added_at TIMESTAMPTZ DEFAULT NOW(),
//     last_state TEXT,
//     current_state TEXT
// );

export function insertNewUser(from: User, db: Database) {
  return db.query(
    `INSERT INTO users (id, bot_id, first_name, last_name, username, current_state)
         VALUES ($1, $2, $3, $4, $5, $6) on conflict (id, bot_id) do update set current_state = EXCLUDED.current_state`,
    [from.id, getBotId(), from.first_name, from.last_name, from.username, 'start'],
  )
}

export function updateUserState(userId: number, state: string, db: Database) {
  return db.query('UPDATE users SET current_state = $1 WHERE id = $2 and bot_id = $3', [state, userId, getBotId()])
}

export async function getUserStates(userId: number, db: Database): Promise<{ current_state: string, previous_state: string } | null> {
  const res = await db.query('SELECT current_state, previous_state FROM users WHERE id = $1 and bot_id = $2', [userId, getBotId()])
  if (res.rows.length === 0) {
    return null
  }
  else {
    return { current_state: res.rows[0].current_state, previous_state: res.rows[0].previous_state }
  }
}

export interface Case {
  id: number
  bot_id: number
  topic: string
  caption: string | null
  videonote: string | null
  video: string | null
  photo: string | null
  audionote: string | null
  audio: string | null
  saved: boolean
}

export async function insertNewCase(topic: string, userId: number, db: Database): Promise<number> {
  return await db.query(
    `INSERT INTO cases (bot_id, topic, creater_id) VALUES ($1, $2, $3) RETURNING id`,
    [getBotId(), topic, userId],
  ).then(res => res?.rows?.[0]?.id ?? Promise.reject(new Error('Failed to insert new case')))
}

export async function getUnsavedCaseByUser(userId: number, db: Database): Promise<Case | null> {
  const res = await db.query('SELECT * FROM cases WHERE creater_id = $1 AND saved = FALSE ORDER BY id DESC LIMIT 1', [userId])
  return res?.rows?.[0] ?? null
}

export function updateCaseByUser(userId: number, mediaField: 'videonote' | 'video' | 'photo' | 'audionote' | 'audio' | 'caption', fileId: string | null, db: Database) {
  const queryText = `UPDATE cases SET ${mediaField} = $1 WHERE creater_id = $2 AND saved = FALSE`
  return db.query(queryText, [fileId, userId])
}

export function saveCaseByUser(userId: number, db: Database) {
  return db.query('UPDATE cases SET saved = TRUE WHERE creater_id = $1 AND saved = FALSE', [userId])
}

export function deleteUnsavedCasesByUser(userId: number, db: Database) {
  return db.query('DELETE FROM cases WHERE creater_id = $1 AND saved = FALSE', [userId])
}

export function getNextCase(db: Database, section: string, lastCaseId: number = -1): Promise<Case | null> {
  return db.query(
    'SELECT * FROM cases WHERE topic = $1 AND id > $2 AND saved = TRUE ORDER BY id ASC LIMIT 1',
    [section, lastCaseId],
  ).then((res) => {
    if (res.rows.length === 0) {
      return db.query(
        'SELECT * FROM cases WHERE topic = $1 AND saved = TRUE ORDER BY id ASC LIMIT 1',
        [section],
      ).then((res) => {
        if (res.rows.length === 0) {
          return null
        }
        return res.rows[0]
      })
    }
    return res.rows[0]
  })
}

// CREATE TABLE media (
//     id SERIAL PRIMARY KEY,
//     message_id TEXT NOT NULL,
//     media_type TEXT NOT NULL,
//     file_id TEXT NOT NULL
// );

export interface MessageMedia {
  id: number
  message_id: string
  media_type: string
  file_id: string
}

export function getMediaForMessage(messageId: string, db: Database): Promise<MessageMedia[]> {
  return db.query('SELECT * FROM media WHERE message_id = $1', [messageId]).then(res => res.rows ?? [])
}
